# Generated by Django 5.2.3 on 2025-06-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Метки'},
        ),
    ]
